-- MySQL Script generated by MySQL Workbench
-- Mon Aug 29 12:33:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema busstation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `busstation` ;

-- -----------------------------------------------------
-- Schema busstation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `busstation` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `busstation` ;

-- -----------------------------------------------------
-- Table `busstation`.`busdata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `busstation`.`busdata` ;

CREATE TABLE IF NOT EXISTS `busstation`.`busdata` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `filterDate` VARCHAR(150) NOT NULL,
  `toDestination` VARCHAR(150) NOT NULL,
  `fromDestination` VARCHAR(150) NOT NULL,
  `price` DOUBLE NOT NULL,
  `BusName` VARCHAR(150) NOT NULL,
  `time` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `BusName_UNIQUE` (`BusName` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Reservation';


-- -----------------------------------------------------
-- Table `busstation`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `busstation`.`user` ;

CREATE TABLE IF NOT EXISTS `busstation`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `busstation`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `busstation`.`bookings` ;

CREATE TABLE IF NOT EXISTS `busstation`.`bookings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `noOfPersons` INT(11) NOT NULL,
  `totalCalculated` DOUBLE NOT NULL,
  `filterDate` VARCHAR(150) NOT NULL,
  `toDestination` VARCHAR(150) NOT NULL,
  `fromDestination` VARCHAR(150) NOT NULL,
  `BusName` VARCHAR(150) NOT NULL,
  `time` VARCHAR(150) NOT NULL,
  `fileName` VARCHAR(150) NOT NULL,
  `tripStatus` TINYINT(1) NOT NULL,
  `userId` INT(11) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `userId_idx` (`userId` ASC) ,
  INDEX `busname_idx` (`BusName` ASC) ,
  CONSTRAINT `busname`
    FOREIGN KEY (`BusName`)
    REFERENCES `busstation`.`busdata` (`BusName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `busstation`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `busstation`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `busstation`.`role` ;

CREATE TABLE IF NOT EXISTS `busstation`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `busstation`.`users_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `busstation`.`users_role` ;

CREATE TABLE IF NOT EXISTS `busstation`.`users_role` (
  `custId` INT(11) NOT NULL,
  `roleId` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `roleId_idx` (`roleId` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `custId`
    FOREIGN KEY (`custId`)
    REFERENCES `busstation`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roleId`
    FOREIGN KEY (`roleId`)
    REFERENCES `busstation`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
